spring:
  profiles: Eureka1
  application:
    name: Eureka
server:
  port: 5551
eureka:
  instance:
    hostname: Eur1
  client: 
   fetch-registry: true
   register-with-eureka: true
   service-url:
     defaultZone: http://Eur2:5552/eureka,http://Eur3:5553/eureka
---
spring:
  profiles: Eureka2
  application:
    name: Eureka
server:
  port: 5552
eureka:
  instance:
    hostname: Eur2
  client: 
   fetch-registry: true
   register-with-eureka: true
   service-url:
     defaultZone: http://Eur1:5551/eureka,http://Eur3:5553/eureka
---
spring:
  profiles: Eureka3
  application:
    name: Eureka
server:    
  port: 5553
eureka:
  instance:
    hostname: Eur3
  client: 
   fetch-registry: true
   register-with-eureka: true
   service-url:
     defaultZone: http://Eur2:5552/eureka,http://Eur1:5551/eureka
